using System;
using NUnit.Framework;
using Tester.TestHere;
using System.Collections.Generic;

[TestFixture]
class ClassForTestsTest
{
    private ClassForTests _classForTests;
    [SetUp]
    public void SetUp()
    {
        _classForTests = new ClassForTests();
    }

    [Test]
    public void IntService()
    {
        var entity = default(CustomEntity);
        var id = default(int);
        var actual = _classForTests.IntService(entity, id);
        var expected = default(int);
        Assert.That(actual, Is.EqualTo(expected));
        Assert.Fail("autogenerated");
    }

    [Test]
    public void DoubleService()
    {
        var s = default(string);
        var actual = _classForTests.DoubleService(s);
        var expected = default(double);
        Assert.That(actual, Is.EqualTo(expected));
        Assert.Fail("autogenerated");
    }

    [Test]
    public void StringService()
    {
        var l = default(long);
        var actual = _classForTests.StringService(l);
        var expected = default(string);
        Assert.That(actual, Is.EqualTo(expected));
        Assert.Fail("autogenerated");
    }

    [Test]
    public void DateTimeService()
    {
        var actual = _classForTests.DateTimeService();
        var expected = default(DateTime);
        Assert.That(actual, Is.EqualTo(expected));
        Assert.Fail("autogenerated");
    }

    [Test]
    public void VoidService()
    {
        _classForTests.VoidService();
        Assert.Fail("autogenerated");
    }
}